# Generated by Django 4.2.8 on 2023-12-12 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('image', models.ImageField(upload_to='promotion/%Y/%m/%d')),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('DISCOUNT', 'Скидка'), ('BONUS', 'Бонус'), ('CERTIFICATE', 'Сертификат')], default='DISCOUNT', max_length=45)),
                ('price', models.PositiveIntegerField()),
                ('contacts', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=85)),
            ],
        ),
    ]
