# Generated by Django 4.2.8 on 2023-12-22 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='new_price',
        ),
        migrations.AddField(
            model_name='promotion',
            name='discount',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='work_time',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.CreateModel(
            name='PromotionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='promotion.promotioncategory')),
            ],
        ),
        migrations.AddField(
            model_name='promotion',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='promotion.promotioncategory'),
        ),
    ]
