# Generated by Django 5.0 on 2023-12-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_myuser_managers_remove_myuser_activation_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='user_images/<django.db.models.fields.CharField>/'),
        ),
    ]
